### ISSUE TITLE
PDF formatı yok, kodlarda yazım vurgulama yok

### ISSUE THREAD

**Issue by tugkan0153** [ksckaan1/go-programlama-dili#23]
Türkçe Go Belgesi hazırladıgınız için teşekürler ancak birkaç sorun var. Öncelikle belge PDF formatında yok yada ben bulamadım. `.epub` ı tabletimde açtım ancak kod örneklerindeki font, anatımda kullanılan font ile aynı, kalın font, renkli font yok yani yazım vurgulama *syntax highlighting* hiç yok bu da kodları incelemeyi zorlaştırıyor. 

Belgede, bu belgenin birçok yorum aldığı belirtilmiş,  onlar arasında buna hiç değinilmedi mi ?

**Comment by ksckaan1** [comment]
Okuduğunuz belge gitbook kopyası, açıkçası yorum alan belge o değil. Daha öncesinde pdf vardı. Ama pdf ve epub canlı güncelleme olmadığı için, aktif olarak gitbook ta yayınlıyorum. go.kaanksc.com adresinden okuyabilirsiniz. Epub dosyasını ise bir kişinin isteği üzerine dönüştürüp ekledim. Bu yorumunuz için vakit ayırdığınızdan dolayı teşekkür ederim

**Comment by tugkan0153** [comment]
Yanıtı şimdi gördüm. GitBook'ta anlık / güncel PDF çıkarma seçeneği var diye biliyorum. Adını yanlış anımsamıyorsam Uğur Yılmazel 'in Ruby 101 adlı belgesi vardı, onu GitBook'tan PDF olarak indirebiliyorduk. ePub özellikle programcılıkla ilgili belgelerde yetersiz. Formata takıldığım için içerik üzerine yorum yapamadım. İçerik iyi. Bu arada ben de programcılık üzerine bir belge yazıyorum. Belgenin adı: **Türkçe Lisp Belgesi** olacak. Yakında Github üzerinden kaynak kodları ile o kodlardan yapılmış PDF'si ile yayınlamayı düşünüyorum.

**Comment by ksckaan1** [comment]
İlginiz için teşekkür ederim. Gitbook'taki PDF Export özelliği sadece ücretli Gitbook planında var. Eğer bir web döküman yazma gibi fikriniz olursa, Docasaurus'u önerebilirim. Kolay gelsin şimdiden
