### ISSUE TITLE
Book yazim hatasi

### ISSUE THREAD

**Issue by adilaxmdv** [ksckaan1/go-programlama-dili#25]
```go
package main

import “fmt”

func main(){
    fmt.Println(“Merhaba Dünya!”)
}
```
burda "" tirnak olmasi gerekiyor belki ebookdan dolayi

**Comment by ksckaan1** [comment]
Evet, döküman genelin böyle bir sorun mevcut. Bildirdiğiniz için teşekkür ederim.
