### ISSUE TITLE
gitbook için light mode aktif edilmesi

### ISSUE THREAD

**Issue by syswe** [ksckaan1/go-programlama-dili#28]
Kaynak çok başarılı cidden elinize sağlık. Google üzerinde aramalarda da web uygulaması üst sıralara çıkabiliyor. 

Ancak bir sorun olarak web uygulamasında Light Mode aktif edilemiyor. Gitbook konfigürasyonlarından Light Mode aktif edilebilme seçeneğini aktif edebilmemiz mümkün mü ?

**Comment by ksckaan1** [comment]
Değerli vaktinizi ayırıp, geri bildirimde bulunduğunuz için teşekkür ederim. GitBook üzerinden dediğiniz ayarı yaptım. Sitenin en altında dark/light mode geçiş özelliği geldi

**Comment by syswe** [comment]
> Değerli vaktinizi ayırıp, geri bildirimde bulunduğunuz için teşekkür ederim. GitBook üzerinden dediğiniz ayarı yaptım. Sitenin en altında dark/light mode geçiş özelliği geldi

Teşekkürler elinize emeğinize sağlık 💯
